# TASK

   -Regras de negocios ( MiniMundo ) 

   1. Modelar um banco ( Entidade, Relacionamento, Entidade-Relacionamento, Cardinalidade)
   2. Criar as tabelas ( Exclusão Lógica )
   3. Criação do Script, gerar 2mil dados aleatórios e inserir no banco
   4. Rodar o Crontab pra executar automaticamente

# Library

In [121]:
from faker import Faker
import pandas as pd
import random
from sqlalchemy import create_engine

In [122]:
fake = Faker('pt_BR')
total_alunos_responsaveis = 2000

# Alunos e Responsáveis

* Tabela Alunos

In [123]:
def gerar_alunos():
    sexo = random.choice(['M', 'F']) 

    if sexo == 'M':
        nome = f"{fake.first_name_male()} {fake.last_name_male()}"  
    else: 
        nome = f"{fake.first_name_female()} {fake.last_name_female()}"  

    return {
        'Nome': nome,
        'Sexo': sexo,
        'Data_Nascimento': fake.date_of_birth(minimum_age=6, maximum_age=18),
        'cep': fake.postcode(),
        'cpf': fake.cpf(),
        'ativo': True 
    }

In [124]:
Alunos = [gerar_alunos() for _ in range(total_alunos_responsaveis)]

In [125]:
df_Alunos = pd.DataFrame(Alunos)

df_Alunos

,Nome,Sexo,Data_Nascimento,cep,cpf,ativo
0,Maria Cecília da Luz,F,2018-12-23,29894-428,763.184.950-10,True
1,Heloisa Peixoto,F,2009-09-23,61314-634,270.439.618-31,True
2,Eduarda Cirino,F,2016-02-16,69039894,827.605.914-76,True
3,Alana Garcia,F,2013-04-13,02281-031,671.480.925-58,True
4,Raul Souza,M,2015-03-15,71033346,136.495.708-66,True
...,...,...,...,...,...,...
1995,Juliana da Conceição,F,2016-01-09,59902380,821.679.054-67,True
1996,Daniela Viana,F,2018-12-04,38284-696,230.846.715-08,True
1997,Mirella Alves,F,2016-06-28,03686679,748.953.601-48,True
1998,Paulo Carvalho,M,2008-10-21,24657361,178.902.635-03,True
1999,Raquel Rodrigues,F,2019-04-14,90388-208,195.368.042-98,True

* Tabela Responsaveis

In [126]:
def gerar_responsaveis():
    sexo = random.choice(['M', 'F']) 

    if sexo == 'M':
        nome = f"{fake.first_name_male()} {fake.last_name_male()}"  
    else: 
        nome = f"{fake.first_name_female()} {fake.last_name_female()}"  

    return {
        'Nome': nome,
        'ativo': True 
    }

In [127]:
Responsaveis = [gerar_responsaveis() for _ in range(total_alunos_responsaveis)]

In [128]:
df_Responsaveis = pd.DataFrame(Responsaveis)

* Criação dos index, tabela Aluno_Responsaveis e organização das tabelas

In [135]:
df_Alunos['id_aluno'] = df_Alunos.index + 1
df_Responsaveis['id_responsavel'] = df_Responsaveis.index + 1

In [130]:
df_aluno_responsavel = pd.DataFrame({'id_aluno' : df_Alunos['id_aluno'], 
                                      'id_responsavel' : df_Responsaveis['id_responsavel'].sample(n=len(df_Alunos), replace=True).values})

In [131]:
df_Alunos = df_Alunos[['id_aluno', 'Nome', 'Sexo', 'Data_Nascimento', 'cep', 'cpf', 'ativo']]
df_Responsaveis = df_Responsaveis[['id_responsavel','Nome','ativo']]

# Test

In [132]:
df_Responsaveis

      id_responsavel                Nome  ativo
0                  1    Benício Silveira   True
1                  2        Maysa Mendes   True
2                  3      Ana Liz da Paz   True
3                  4  Davi Lucca da Cruz   True
4                  5     Alexia Ferreira   True
...              ...                 ...    ...
1995            1996          Jade Lopes   True
1996            1997         Davi Novaes   True
1997            1998       Aurora Araújo   True
1998            1999        Paulo Campos   True
1999            2000     Theodoro Vargas   True

[2000 rows x 3 columns]

In [133]:
df_aluno_responsavel

      id_aluno  id_responsavel
0            0             174
1            1             954
2            2             250
3            3            1168
4            4             942
...        ...             ...
1995      1995              63
1996      1996            1039
1997      1997             725
1998      1998             576
1999      1999             128

[2000 rows x 2 columns]

In [134]:
df_Alunos

,id_aluno,Nome,Sexo,Data_Nascimento,cep,cpf,ativo
0,0,Maria Cecília da Luz,F,2018-12-23,29894-428,763.184.950-10,True
1,1,Heloisa Peixoto,F,2009-09-23,61314-634,270.439.618-31,True
2,2,Eduarda Cirino,F,2016-02-16,69039894,827.605.914-76,True
3,3,Alana Garcia,F,2013-04-13,02281-031,671.480.925-58,True
4,4,Raul Souza,M,2015-03-15,71033346,136.495.708-66,True
...,...,...,...,...,...,...,...
1995,1995,Juliana da Conceição,F,2016-01-09,59902380,821.679.054-67,True
1996,1996,Daniela Viana,F,2018-12-04,38284-696,230.846.715-08,True
1997,1997,Mirella Alves,F,2016-06-28,03686679,748.953.601-48,True
1998,1998,Paulo Carvalho,M,2008-10-21,24657361,178.902.635-03,True
1999,1999,Raquel Rodrigues,F,2019-04-14,90388-208,195.368.042-98,True